- name: Demo on conditions
  hosts: localhost
  tasks:
    - name: Print Linux
      ansible.builtin.debug:
       msg: Hello Linux
    - name: Print Unix
      ansible.builtin.debug:
       msg: Hello Unix
    - name: Print Windows
      ansible.builtin.debug:
        msg: Hello Windows



