- name: Demo on loop
  hosts: localhost
  tasks:
    - name: Loop
      ansible.builtin.debug:
        msg: Fruit - {{ item }}
        loop:
          - Apple
          - Banana
          - Mango

- name: Demo on loop
  hosts: localhost
  vars:
    fruits:
      - Mango
      - Apple
      - Guava
  tasks:
    - name: Loop
      ansible.builtin.debug:
        msg: Fruit - {{ item }}
        loop: "{{fruits}}"
